# Generated by Django 4.0 on 2024-02-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0002_alter_category_options_remove_device_zoom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.device')),
            ],
            bases=('device.device',),
        ),
    ]
