# Generated by Django 4.0 on 2024-02-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.device')),
                ('zoom', models.CharField(max_length=255)),
                ('cell', models.CharField(max_length=255)),
            ],
            bases=('device.device',),
        ),
    ]
