# Generated by Django 5.0.2 on 2024-02-13 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phone", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phone",
            name="images",
        ),
        migrations.AddField(
            model_name="image",
            name="phones",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="phone.phone",
            ),
        ),
    ]
