# Generated by Django 4.0 on 2024-02-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='zoom',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
