# Generated by Django 4.0 on 2024-02-16 20:59

import device.google_image_field
import device.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hex_value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=255)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'verbose_name_plural': 'memories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('url', device.google_image_field.GoogleImageField(null=True, upload_to=device.models.devices_image_file_path)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.color')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.category')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('screen', models.CharField(max_length=255)),
                ('resolution', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('camera', models.CharField(max_length=255)),
                ('year_of_creation', models.IntegerField(null=True)),
                ('about', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.category')),
                ('colors', models.ManyToManyField(to='device.Color')),
                ('images', models.ManyToManyField(to='device.Image')),
                ('memories', models.ManyToManyField(to='device.Memory')),
            ],
        ),
    ]
