# Generated by Django 4.0 on 2024-02-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_category_options_remove_device_zoom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='price',
        ),
        migrations.AddField(
            model_name='device',
            name='year_of_creation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
